### ISSUE TITLE
请问一下Relational Correlation Module的代码是哪个？

### ISSUE THREAD

**Issue by siberia0015** [MIRALab-USTC/KG-TACT#4]
想请问一下前辈模型中的Relational Correlation Module的代码在哪个文件呢？看了一下没有找到相关代码。

**Comment by JiajunChen98** [comment]
你好，模型的主要实现在 model/dgl/graph_classifier.py 文件的  GraphClassifier 类。

**Comment by siberia0015** [comment]
好的，感谢！
