### ISSUE TITLE
找不到relation2id.json

### ISSUE THREAD

**Issue by siberia0015** [MIRALab-USTC/KG-TACT#5]
前辈您好，运行代码报错FileNotFoundError: [Errno 2] No such file or directory: 'utils/../../../data/WN18RR_v1_ind/relation2id.json'，请问这个文件要去哪里找呢？

**Comment by JiajunChen98** [comment]
请问问题解决了吗？没解决的话可以附上更加详细的说明吗？你是怎么配置环境的，运行了哪些指令？这个文件是在第一次运行代码生成的，如果有正确配置好环境，应该不会出现这个问题。

**Comment by JiajunChen98** [comment]
> 前辈您好，运行代码报错FileNotFoundError: [Errno 2] No such file or directory: 'utils/../../../data/WN18RR_v1_ind/relation2id.json'，请问这个文件要去哪里找呢？

请问问题解决了吗？没解决的话可以附上更加详细的说明吗？你是怎么配置环境的，运行了哪些指令？这个文件是在第一次运行代码生成的，如果有正确配置好环境，应该不会出现这个问题。

**Comment by deepocean1226** [comment]
我好像也遇到了相同的问题，因为3.7现在已经不支持requirements.txt里的版本，因此我用了一个其他的环境版本可能有细微差别，但是我生成的relation2id是在WN18RR_v1文件夹内的，而不是在ind文件夹内的，请问作者这种情况是正常的吗？
