### ISSUE TITLE
About YAGO3-10 dataset

### ISSUE THREAD

**Issue by hykwak** [MIRALab-USTC/KG-TACT#7]
Hi, thanks for sharing your code!
In your paper, experimental results on YAGO3-10 were reported.
Is this dataset developed for inductive setting such as other inductive KGC benchmark? 
Or did you modified the original YAGO3-10 for inductive setting?
If you modified it, could you please share us the modified dataset?

**Comment by JiajunChen98** [comment]
Thanks for your interest in our work and sorry for not noting your issue.
We construct the dataset follow the setting of GraIL. In fact, we use the code of GraIL to construct the dataset of YAGO3-10 in the inductive setting. Maybe you can find the code and construct in yourself.
If you have any further questions, welcome to email me. My email address is jiajun98@mail.ustc.edu.cn.
